Split and rewrite
Use tools to do specific jobs.
Change configure when building containers from ISO.

diff --git a/src/depinstc b/src/depinstc
--- a/src/depinstc
+++ b/src/depinstc
@@ -1,99 +1,59 @@
 #!/bin/bash
 
 main() {
-	setup_variables
-	add_generic_mount_points
-	fill_ARGS "$@"
+	_USE_OPRT=0
+	[[ "$(which oprt 2>/dev/null)" == "" ]] || _USE_OPRT=1 
+
+	[[ -d $SHARED_SRC ]] || SHARED_SRC=auto
+
+	_FUNC=${BASH_SOURCE%/*}/func
+
+	fill_ARGS_with_port_dirs "$@"
 
 	# Because recursive_install runs in a sub-shell,
-	# all these variables will be "new" for every _PORT_ARG
+	# all these variables will be cleared for every _PORT_DIR
 	declare -A _PORTS_SEEN
  	_PKG_NO=0
-	for _PORT_ARG in "${_ARGS[@]}"; do
-		(
-			recursive_install "$_PORT_ARG"
-		) || {
-			echo "ERROR: port failed: $_PORT_ARG" >&2
-			exit 1
-		}
+	for _PORT_DIR in "${_ARGS[@]}"; do
+		( recursive_install "$_PORT_DIR" ) \
+			|| fatal_error "port failed: $_PORT_DIR"
 	done
 }
 
-setup_variables() {
-	[[ -d $FUNC_COW_BASE ]] || FUNC_COW_BASE=$HOME/tmp
-	[[ -d $FUNC_ROOT     ]] || FUNC_ROOT=/var/cache/func-root
-	[[ -d $SHARED_PKG    ]] || {
-		SHARED_PKG="$FUNC_COW_BASE/shared_pkg"
-		[[ -d $SHARED_PKG ]] \
-			|| mkdir --parents "$SHARED_PKG"
-	}
-
-	export FUNC_BIND FUNC_BIND_RO FUNC_COW_BASE FUNC_COW FUNC_ROOT
-
-	local _DIRS=($(
-		. /etc/pkgmk.conf
-		echo $PKGMK_SOURCE_DIR
-		echo $PKGMK_PACKAGE_DIR
-		echo $PKGMK_WORK_DIR
-	))
-
-	PKGMK_SOURCE_DIR=${_DIRS[0]%%/}
-	PKGMK_PACKAGE_DIR=${_DIRS[1]%%/}
-	PKGMK_WORK_DIR=${_DIRS[2]%%/}
+fatal_error() {
+	printf "ERROR: %s\n" "$*" >&2
+	exit 1
 }
 
-add_generic_mount_points() {
-	[[ -d $SHARED_SRC && $FUNC_ROOT != / ]] \
-		|| SHARED_SRC=$PKGMK_SOURCE_DIR
-
-	FUNC_BIND+=" $SHARED_SRC:$PKGMK_SOURCE_DIR $PKGMK_WORK_DIR"
-
-	[[ -d "$HOME/.cache/pp" ]] && {
-		if [[ $FUNC_ROOT == / ]]; then
-			FUNC_BIND+="    $HOME/.cache/pp"
-			FUNC_BIND_RO+=" $HOME/.cache/pp"
-		else
-			FUNC_BIND+="    $HOME/.cache/pp:/home/u/.cache/pp"
-			FUNC_BIND_RO+="                 /home/u/.cache/pp"
-
-			# keep $HOME to avoid findredundantdeps errors
-			# without removing the directory from prt-get.conf
-			FUNC_BIND+="    $HOME/.cache/pp"
-			FUNC_BIND_RO+=" $HOME/.cache/pp"
-		fi
-	}
-
-	[[ ${CCACHE_DIR+defined} ]]                     \
-		&& [[ $FUNC_ROOT != / ]]                \
-		&& [[ -x "$FUNC_ROOT/usr/bin/ccache" ]] \
-		&& FUNC_BIND+=" $CCACHE_DIR:/var/cache/ccache"
-}
-
-fill_ARGS() {
+fill_ARGS_with_port_dirs() {
 	local _A
 
 	for _A in ${@:-$PWD}; do
-		[[ -e "$_A" ]] || {
+		_A=$(readlink -f "$_A")
+
+		is_port_dir "$_A" || {
 			_A="$(get_port_dir "${_A##*/}")"
-			[[ -e "$_A" ]] || {
-				echo "ERROR: Can't find port: $_A" >&2
-				exit 1
-			}
+			is_port_dir "$_A" \
+				|| fatal_error "Can't find port: $_A"
 		}
 			
-		_ARGS+=( $(readlink -f "$_A") )
+		_ARGS+=( $_A )
 	done
+}
+
+is_port_dir() {
+	[[ -e "$1/Pkgfile" ]]
 }
 
 get_port_dir() {
 	local     _NAME=$1
 	local _PORT_DIR
 
-	if [[ ${DEPINSTC_USE_PRT_GET+defined} ]]; then
-		_PORT_DIR="$(prt-get path "$_NAME")"
-	else
+	if (( $_USE_OPRT == 1 )); then
 		local _COLS=( $(oprt-collections "$_NAME") )
 		_PORT_DIR="${_COLS[0]}/$_NAME"
+	else
+		_PORT_DIR="$(prt-get path "$_NAME")"
 	fi
 
 	printf '%s\n' "$(readlink -f "$_PORT_DIR")"
@@ -137,13 +97,14 @@ already_seen() {
 pkgfile_deps() {
 	local _PORT_DIR=$1
 
-	[[ -x "$(which oprt-pkgfile-deps)" ]] && {
+	if (( $_USE_OPRT == 1 )); then
 		oprt-pkgfile-deps "$_PORT_DIR"
-		return
-	}
-
-	awk '(NF > 1) { print $2 }' FS="Depends on:" < "$_PORT_DIR/Pkgfile" \
+	else
+		awk '(NF > 1) { print $2 }'      \
+			FS="Depends on:"         \
+			< "$_PORT_DIR/Pkgfile"   \
 		| sed -e 's/,/ /g' -e 's/  / /g'
+	fi
 }
 
 install_port() {
@@ -155,44 +116,45 @@ install_port() {
 
 	_PKG_NO=$(( $_PKG_NO + 1 ))
 
-	printf '======= %s (%s) [%d] @ %(%F %T)T\n' "$_PORT_DIR" "${_PORT_ARG##*/}" "$_PKG_NO" -1
+	printf '======= %s (%s) [%d] @ %(%F %T)T\n' "$_PORT_DIR" "${_PORT}" "$_PKG_NO" -1
 
 	cd -- "$_PORT_DIR" \
 		|| return $_STOP
 
 	setup_container "$_PORT_DIR"
 
-	is_port_up_to_date && {
-		rm --recursive --force "$FUNC_COW"
-		return $_CONTINUE
-	}
-
 	# Signing inside the container won't work when we use namespaces
 	# and the (faked) root doesn't have access to the SEC_KEY
 	# Eg. on a mounted fuse directory, like encfs.
 	# Also, the signature file has to be created before the build
-	# to avoid the creation of .md5sum (when it not supported for this repo)
-
+	# to avoid .md5sum creation (when it is not supported for this repo)
 	[[ -e "$FUNC_COW/is_our_arg" ]] \
 		&& make_port_signature
 
-	install_port_in_container "$_PORT_DIR" || {
-		export FUNC_PROOT=1
-		install_port_in_container "$_PORT_DIR"
-	} || { 
-		show_oprt_build_log
-		return $_STOP
-	}
+	[[ -d $SHARED_PKG ]] \
+		|| SHARED_PKG=$(. /etc/pkgmk.conf; echo "$PKGMK_PACKAGE_DIR")
 
-	[[ -e "$FUNC_COW/is_our_arg" ]] && {
-		check_port "$_PORT" \
-			|| return $_STOP
+	# make sure we export variables from our environment
+	# when started as FUNC_ROOT=... depinstc
+	export FUNC_ROOT FUNC_COW FUNC_PROOT
+
+	inject="$_FUNC clone auto auto ports pkgmk $SHARED_SRC $SHARED_PKG oprt prt-get ccache chroot"
+
+	is_port_up_to_date || {
+		install_port_in_container "$_PORT_DIR" || {
+			FUNC_PROOT=1
+			install_port_in_container "$_PORT_DIR"
+		} || return $_STOP
+
+		[[ -e "$FUNC_COW/is_our_arg" ]] && {
+			make_port_signature # with the new footprint
+			check_port "$_PORT" \
+				|| return $_STOP
+		}
 	}
 
 	make_pkg_signature
-
 	rm --recursive --force "$FUNC_COW"
-
 	return $_CONTINUE
 }
 
@@ -200,42 +162,18 @@ setup_container() {
 	local _PORT_DIR=$1
 	local     _PORT=${_PORT_DIR##*/}
 
-	setup_container_dir "$_PORT"
-
-	if [[ $FUNC_ROOT == / ]]; then
-		FUNC_BIND+=" $PKGMK_PACKAGE_DIR"
-		create_file_in_container "full_root"
-	else
-		FUNC_BIND+=" $SHARED_PKG:$PKGMK_PACKAGE_DIR"
-
-		# oprt specific
-		copy_file_in_container                          \
-			"$HOME/.cache/oprt/stats_collections"   \
-			"/home/u/.cache/oprt/stats_collections"
-		copy_file_in_container                          \
-			"$HOME/.cache/oprt/user_collections"    \
-			"/home/u/.cache/oprt/user_collections"
-	fi
-
-	is_our_arg "$_PORT_DIR" \
-		&& create_file_in_container "is_our_arg"
-
-	[[ ${CCACHE_DIR+defined} && -x "$FUNC_ROOT/usr/bin/ccache" ]] \
-		&& create_file_in_container "use_ccache"
-
-	[[ ${DEPINSTC_USE_PRT_GET+defined} ]] \
-		|| create_file_in_container "use_oprt"
-}
-
-setup_container_dir() {
-	local _PORT=$1
-
-	FUNC_COW="$FUNC_COW_BASE/depinstc.$_PORT"
+	FUNC_COW="$HOME/tmp/depinstc.$_PORT"
 
 	[[ -d $FUNC_COW ]] \
 		&& rm --recursive --force "$FUNC_COW"
 
 	mkdir --parents "$FUNC_COW"
+
+	[[ $FUNC_ROOT == / ]] \
+		&& create_file_in_container "full_root"
+
+	is_our_arg "$_PORT_DIR" \
+		&& create_file_in_container "is_our_arg"
 }
 
 create_file_in_container() {
@@ -244,24 +182,16 @@ create_file_in_container() {
 	touch "$FUNC_COW/$_FILE"
 }
 
-copy_file_in_container() {
-	local  _SRC=$1
-	local _DEST=$2
-
-	[[ -e "$_SRC" ]] || return
-
-	_DEST="$FUNC_COW/$_DEST"
-
-	local _DEST_DIR=${_DEST%/*}
-
-	mkdir --parents "$_DEST_DIR"
-
-	cp -- "$_SRC" "$_DEST"
-}
-
 is_our_arg() {
 	local _RE=" $1 "
 	[[ " ${_ARGS[@]} " =~ $_RE ]]
+}
+
+is_port_up_to_date() {
+	local _MATCH="^=======> Package '(.*)' is up to date\.\$"
+
+	local _TEXT=$($inject pkgmk --up-to-date)
+	[[ "$_TEXT" =~ $_MATCH ]]
 }
 
 make_port_signature() {
@@ -275,18 +205,12 @@ make_port_signature() {
 }
 
 make_pkg_signature() {
-	[[ -e $SEC_KEY ]] \
-		|| return
+	[[ -e $SEC_KEY ]]  || return
+	is_port_up_to_date || return
 
-	is_port_up_to_date \
-		|| return
+	local _TARGET="$SHARED_PKG/${BASH_REMATCH[1]##*/}"
 
-	local _TARGET=${BASH_REMATCH[1]##*/}
-	if [[ $FUNC_ROOT == / ]]; then
-		_TARGET="$PKGMK_PACKAGE_DIR/$_TARGET"
-	else
-		_TARGET="$SHARED_PKG/$_TARGET"
-	fi
+	set -o pipefail
 
 	sha256sum --tag "$_TARGET"                                      \
 		| sed 's|^SHA256 (.*/\(.*\))\(.* = .*\)|SHA256 (\1)\2|' \
@@ -303,19 +227,10 @@ install_port_in_container() {
 	local _PORT_DIR=$1
 	local     _PORT=${_PORT_DIR##*/}
 
-	func bash <(
-		declare -f                                \
-			container_build_port              \
-			container_disable_install_scripts \
-			container_is_port_up_to_date      \
-			container_make_dependent_list     \
-			container_is_port_installed       \
-			container_select_build_CMD
-
-		printf 'container_build_port "%s" \n' "$_PORT"
-	)
-
-	(( $? == 0 )) || return $?
+	$inject bash < <(
+		sed "s/^main \"\$@\"\$/container_build_port $_PORT/" \
+			< $BASH_SOURCE
+	) || return $?
 
 	remove_dependent_packages "$_PORT"
 
@@ -325,48 +240,35 @@ install_port_in_container() {
 container_build_port() {
 	local _PORT=$1
 
-	container_is_port_up_to_date \
-		&& touch /up-to-date
-
 	[[ -e /full_root ]] \
 		&& container_disable_install_scripts
 
-	[[ -e /up-to-date ]] \
-		|| container_make_dependent_list "$_PORT"
+	container_make_dependent_list "$_PORT"
 
 	local _CMD
 	container_select_build_CMD "$_PORT"
 
-	[[ -e /use_ccache && ! -e /up-to-date ]] \
-		&& ccache --zero-stats
+	local ccache=$(which ccache 2>/dev/null)
+	[[ $ccache == "" ]] && ccache=":"
+
+	$ccache --zero-stats
 
 	printf '%s\n' "$_CMD"
 
 	$_CMD \
 		|| exit 1
 
-	[[ -e /use_ccache && ! -e /up-to-date  ]] \
-		&& ccache --show-stats | grep "cache hit rate"
+	$ccache --show-stats | grep "cache hit rate"
 
 	exit 0
 }
 
 container_disable_install_scripts() {
-	mkdir --parents "$HOME/.cache/oprt"
-	echo > ${HOME}/.cache/oprt/run_script
-	sed 's/runscripts.*//' --in-place /etc/prt-get.conf
-}
-
-container_is_port_up_to_date() {
-	local _MATCH="^=======> Package '(.*)' is up to date\.\$"
-
-	[[ "$(pkgmk --up-to-date)" =~ $_MATCH ]]
-}
-
-is_port_up_to_date() {
-	local _MATCH="^=======> Package '(.*)' is up to date\.\$"
-
-	[[ "$(func bash pkgmk --up-to-date)" =~ $_MATCH ]]
+	export OPRT_DONT_RUN_SCRIPTS=lilo_fails_installing_kernel
+	ed -s /etc/prt-get.conf <<-EOF
+		g/runscripts/d
+		w
+	EOF
 }
 
 container_make_dependent_list() {
@@ -374,8 +276,8 @@ container_make_dependent_list() {
 
 	printf 'REBUILD: %s - %s\n' "$_PORT" "${BASH_REMATCH[1]}"
 
-	if [[ -e /use_oprt ]]; then
-		export OPRT_DEPSEARCH_BASIC=1
+	if [[ -x "$(which oprt 2>/dev/null)" ]]; then
+		export OPRT_DEPSEARCH_BASIC=only_installed_ports_depending_on_this
 		oprt-depsearch "$_PORT" 2>/dev/null    \
 				| grep '^Name:'        \
 				| awk '{print $2}'     \
@@ -388,23 +290,23 @@ container_make_dependent_list() {
 container_select_build_CMD() {
 	local _PORT=$1
 
-	if [[ -e /use_oprt ]]; then
-		export OPRT_BUILD_WITH_FAKEROOT=1
-		export OPRT_DONT_ASK_SCRIPT=1
+	if [[ -x "$(which oprt 2>/dev/null)" ]]; then
+		export OPRT_BUILD_WITH_FAKEROOT=needed_by_some_ports
+		export OPRT_DONT_RUN_SCRIPTS=lilo_fails_installing_kernel
+		export OPRT_DONT_ASK_SCRIPT=we_dont_run_scripts
+		export OPRT_DONT_LOG=do_not_pollute_the_log_if_mounted
 		_CMD=oprt-depinst
-		[[ -e /is_our_arg ]] && {
-			export OPRT_INSTALL_WITH_FORCE=1
-			export OPRT_INSTALL_IGNORING_FOOTPRINT=1
-		}
 		container_is_port_installed "$_PORT"        \
 			&& [[ -e /rebuild_for_dependents ]] \
 			&& _CMD=oprt-reinstall
+		[[ -e /is_our_arg ]] && {
+			export OPRT_INSTALL_WITH_FORCE=do_not_care
+			export OPRT_INSTALL_IGNORING_FOOTPRINT=not_footprinted_yet
+		}
 	else
-		_CMD="prt-get depinst $_PORT"
-		prt-get isinst "$_PORT" \
-			&& _CMD="prt-get update $_PORT"
-		[[ -e /is_our_arg ]] \
-			&& _CMD+=" -if -fi"
+		                           _CMD="prt-get depinst $_PORT"
+		prt-get isinst "$_PORT" && _CMD="prt-get update  $_PORT"
+		[[ -e /is_our_arg ]]    && _CMD+=" -if -fi"
 	fi
 }
 
@@ -419,7 +321,7 @@ remove_dependent_packages() {
 
 	[[ -e "$FUNC_COW/rebuild_for_dependents" ]] || return
 
-	local _DEPENDENTS _PKG _PORT
+	local _DEPENDENTS _PKG _DEP
 
 	readarray -t $_DEPENDENTS < "$FUNC_COW/rebuild_for_dependents"
 
@@ -436,29 +338,14 @@ remove_dependent_packages() {
 	return 0
 }
 
-show_oprt_build_log() {
-	[[ ${DEPINSTC_USE_PRT_GET+defined} ]] || return
-
-	local _FAILED=( $FUNC_COW/home/u/.cache/oprt/*.failed )
-	local _LOG=${_FAILED[0]}
-
-	[[ -e $_LOG ]] || return
-
-	echo '>>>'
-	echo '>>> the last 100 lines from the build log'
-	echo '>>>'
-	tail -n 100 "$_LOG"
-
-	printf 'Log: %s\n' "$_LOG"
-}
-
 check_port() {
 	local _PORT=$1
 
-	func bash <<-EOF
+	# pkgmk --update-footprint
+
+	$inject bash <<-EOF
 	set -o errexit
 	set -o xtrace
-	pkgmk --update-footprint
 	revdep "$_PORT"
 	prtverify .
 	finddeps "$_PORT"
diff --git a/src/func-configure b/src/func-configure
--- a/src/func-configure
+++ b/src/func-configure
@@ -1,119 +1,12 @@
 #!/bin/bash
 
-main() {
-	local chroot_dir=$1
+if (( $UID == 0 )); then
+	type=configure-root
+else
+	printf 'ERROR: unsupported non-root for the time being\n'
+	exit 1
+fi
 
-	setup_pkgmk_dirs "$chroot_dir"
+set -- $type "$@"
 
-	cp --archive --verbose     \
-		/etc/resolv.conf   \
-		/etc/localtime     \
-		"$chroot_dir/etc/"
-
-	local func_chroot=${BASH_SOURCE%/*}/func-chroot
-
-	export FUNC_ROOT=$chroot_dir
-
-	$func_chroot bash <(
-		declare -f container_config
-		echo       container_config
-	)
-
-	$func_chroot rejmerge
-}
-
-setup_pkgmk_dirs() {
-	local chroot_dir=$1
-
-	[[ -e "$chroot_dir/default_dirs" ]] || {
-		cat <<-EOF
-		PKGMK_SOURCE_DIR  /var/cache/src
-		PKGMK_PACKAGE_DIR /var/cache/pkg
-		PKGMK_WORK_DIR    /var/cache/work
-		EOF
-	} > "$chroot_dir/default_dirs"
-}
-
-container_config() {
-	set -o errexit
-	set -o xtrace
-
-	sed -e '/PS1/d' -e '/PS2/d' --in-place /etc/profile
-	(
-		printf 'export PS1="%s"\n' ": \w ; "
-		printf 'export PS2="%s"\n' " "
-		grep LANG= /etc/profile >/dev/null \
-			|| echo 'export LANG=en_US.UTF-8'
-	) >> /etc/profile
-
-	while read -r name dir; do
-		! egrep "^\\s*$name=" /etc/pkgmk.conf >/dev/null \
-			|| continue
-		[[ -d $dir ]] \
-			|| mkdir --parents "$dir"
-		echo "$name=$dir" >> /etc/pkgmk.conf
-	done < /default_dirs
-
-	# setup language to avoid some warnings/errors
-	localedef --inputfile=en_US --charmap=UTF-8 en_US.UTF-8
-
-	# therealfun repo
-	cat >/etc/ports/therealfun.httpup <<-EOF
-	ROOT_DIR=/usr/ports/therealfun
-	URL=https://raw.githubusercontent.com/therealfun/crux-ports/master/
-	EOF
-	cat >/etc/ports/therealfun.pub <<-EOF
-	untrusted comment: therealfun public key
-	RWTcI5d5qAlZ8u0wrrc4B6AbKFmqJgZWHnYQq+6HxIoFsKc5S0EJkJMm
-	EOF
-	egrep 'therealfun' /etc/prt-get.conf \
-		|| echo prtdir /usr/ports/therealfun >>/etc/prt-get.conf
-
-	# enable inactive ports
-	for repo in /etc/ports/*.{rsync,git,httpup}.inactive; do
-		[[ -e $repo ]] || continue
-		mv $repo ${repo%.inactive}
-		name=${repo##*/}
-		echo prtdir /usr/ports/${name%%.*} >>/etc/prt-get.conf
-		
-	done
-
-	# update ports
-	ports --update || true
-
-	# Set 'runscripts' to NO unless is already configured.
-	# It flags that we have run the post-install scripts.
-	egrep '^\s*runscripts' /etc/prt-get.conf || (
-		prt-get listinst \
-			| xargs --max-args=1 prt-get path \
-			| xargs --max-args=1 --replace=pk \
-				sh -c 'test -f pk/post-install && sh -x pk/post-install' \
-			|| true
-		echo 'runscripts no' >> /etc/prt-get.conf
-	)
-
-	egrep '^\s*makecommand' /etc/prt-get.conf || (
-		echo 'makecommand nice --adjustment=19 ionice --class idle pkgmk' \
-			>> /etc/prt-get.conf
-	)
-
-	# upgrade pkgutils first
-	prt-get update pkgutils --install-scripts
-
-	# hard to live without these
-	prt-get depinst fakeroot prt-utils ccache oprt --install-scripts
-
-	# clean-up
-	rm /var/cache/src/* /var/cache/pkg/* || true
-
-	# setup ccache to the safest (slow) mode unless is already configured
-	grep CCACHE_DIR /etc/profile || (
-		mkdir --parents /var/cache/ccache
-		echo 'export CCACHE_DIR=/var/cache/ccache'
-		echo 'export CCACHE_COMPILERCHECK="string:\$(gcc -dumpversion; crux)"'
-		echo 'export CCACHE_NODIRECT=1'
-		echo 'export PATH="/usr/lib/ccache:\$PATH"'
-	) >> /etc/profile
-}
-
-main ${1:-/var/cache/func-root}
+. ${BASH_SOURCE%/*}/func
diff --git a/src/func-create b/src/func-create
--- a/src/func-create
+++ b/src/func-create
@@ -1,99 +1,12 @@
 #!/bin/bash
 
-main() {
-	local chroot_dir=$1
+if (( $UID == 0 )); then
+	type=create-root
+else
+	printf 'ERROR: unsupported non-root for the time being\n'
+	exit 1
+fi
 
-	(( $UID == 0 )) || { printf 'ERROR: run as root\n'; exit 1; }
+set -- $type "$@"
 
-	shopt -s nullglob dotglob
-	local files=( $chroot_dir/* )
-	shopt -u nullglob dotglob
-	(( ${#files[*]} )) && { printf 'ERROR: %s already exists\n' "$chroot_dir"; exit 1; }
-
-	local m
-	for m in $(get_https_mirrors); do
-		valid_mirror "$m"                               \
-			&& build_from_mirror "$chroot_dir" "$m" \
-			&& exit 0
-	done
-}
-
-get_https_mirrors() {
-	wget                                                      \
-		--quiet                                           \
-		--timeout=30                                      \
-		--output-document=- https://crux.nu/Main/Download \
-	| perl -ne "
-		print(\$1,\"\n\") if m,href=['\"](.+?)['\"].+?>HTTP<,i;
-	" \
-	| sed -e 's,^http:,https:,' -e 's,^ftp:,https:,' \
-	| shuf
-}
-
-valid_mirror() {
-	local mirror=$1
-	local current_ver=$(crux | awk '{print $3; exit}')
-	local loop_ver=$(
-		wget --quiet --timeout=10 --tries=1 "${mirror}loop/crux/releasenotes.txt" -O- \
-		| head -1 \
-		| awk '{print $5; exit}')
-	[[ $current_ver == $loop_ver ]]
-}
-
-build_from_mirror() {
-	local chroot_dir=$1
-	local     mirror=$2
-
-	local pkg_dir="$chroot_dir.pkg"
-
-	remove_dir      "$pkg_dir" || return 1
-	mkdir --parents "$pkg_dir" || return 1
-
-	wget "${mirror}loop/crux/core/"       \
-		--timeout=10                  \
-		--tries=3                     \
-		--recursive                   \
-		--level 1                     \
-		--no-clobber                  \
-		--no-host-directories         \
-		--no-directories              \
-		"--directory-prefix=$pkg_dir" \
-		--no-hsts                     \
-		--accept '*.pkg.tar.xz'       \
-		|| return 1
-
-	build "$chroot_dir" "$pkg_dir"
-}
-
-remove_dir() {
-	local dir=$1
-
-	[[ -d $dir ]] && {
-		rm --recursive --force "$dir" \
-			|| return 1
-	}
-
-	return 0
-}
-
-build() {
-	local chroot_dir=$1
-	local    pkg_dir=$2
-
-	remove_dir      "$chroot_dir"                || return 1
-	mkdir --parents "$chroot_dir/var/lib/pkg"    || return 1
-	touch           "$chroot_dir/var/lib/pkg/db" || return 1
-
-	local p
-	for p in $pkg_dir/*; do
-		printf 'Installing %s\n' "${p##*/}"
-		pkgadd --root "$chroot_dir" "$p" \
-			|| return 1
-	done
-
-	remove_dir "$pkg_dir"
-
-	return 0
-}
-
-main ${1:-/var/cache/func-root}
+. ${BASH_SOURCE%/*}/func
diff --git a/src/sysupc b/src/sysupc
--- a/src/sysupc
+++ b/src/sysupc
@@ -1,94 +1,65 @@
 #!/bin/bash
 
-main() {
-	setup_variables
+run_me_in_container() {
+	export FUNC_DONT_BIND_CWD=not_needed
+	exec ${BASH_SOURCE%/*}/func      \
+		clone        /    auto   \
+		pkgmk        auto auto   \
+		ccache                   \
+		oprt                     \
+		prt-get                  \
+		chroot                   \
+		bash < <(
+			sed 's/^run_me_in_container$/run_me/' \
+				< $BASH_SOURCE
+		)
+}
 
-	if [[ ${SYSUPC_USE_PRT_GET+defined} ]]; then
-		system_upgrade_with_prt_get
+run_me() {
+	if have_oprt; then
+		sysupc_with_oprt
 	else
-		system_upgrade_with_oprt
+		sysupc_with_prt_get
 	fi
 }
 
-setup_variables() {
-	local _DIRS=($(
-		. /etc/pkgmk.conf
-		echo $PKGMK_PACKAGE_DIR
-		echo $PKGMK_SOURCE_DIR
-	))
+have_oprt() {
+	oprt=$(which oprt)
 
-	export FUNC_BIND+=" ${_DIRS[@]}"
-	export FUNC_DONT_EXPORT_CWD=1
-	export FUNC_ROOT=/
+	[[ -x $oprt ]]
+}
+
+sysupc_with_oprt() {
+	export OPRT_BUILD_WITH_FAKEROOT=needed_by_some_ports
+	export OPRT_INSTALL_WITH_FORCE=do_not_care
+	export OPRT_SKIP_REJMERGE=do_not_care_rejmerge
+	export OPRT_DONT_LOG=do_not_pollute_the_log_if_mounted
+	export OPRT_DONT_RUN_SCRIPTS=lilo_fails_installing_kernel
+	export OPRT_DONT_ASK_SCRIPT=we_dont_run_scripts
+
+	# avoid rebuilding some big packages
+	[[ ${REVDEP_OPTS+defines} ]] \
+		&& export OPRT_REVDEP=$REVDEP_OPTS
+
+	set -o xtrace
+	oprt-update
+}
+
+sysupc_with_prt_get() {
+	# lilo fails installing linux-stable
+	ed -s /etc/prt-get.conf <<-EOF
+		g/runscripts/d
+		w
+	EOF
+
+	set -o xtrace
+	prt-get sysup || exit 1
 
 	[[ ${REVDEP_OPTS+defined} ]] \
 		|| REVDEP_OPTS="-i libreoffice"
-	export REVDEP_OPTS="${REVDEP_OPTS//[^a-zA-Z0-9 -]/}"
-}
+	REVDEP_OPTS="${REVDEP_OPTS//[^a-zA-Z0-9 -]/}"
 
-system_upgrade_with_prt_get() {
-	func bash <(
-		declare -f                    \
-			ccache_reset_stats    \
-			ccache_show_stats     \
-			is_ccache_enabled     \
-			upgrade_with_prt_get
-
-		echo   "upgrade_with_prt_get"
-	)
-}
-
-system_upgrade_with_oprt() {
-	# we need fakeroot because of ports like dcron, dbus
-	export OPRT_BUILD_WITH_FAKEROOT=1
-	export OPRT_INSTALL_WITH_FORCE=1
-	export OPRT_SKIP_REJMERGE=1
-	export OPRT_REVDEP=$REVDEP_OPTS
-
-	func bash <(
-		declare -f                 \
-			ccache_reset_stats \
-			ccache_show_stats  \
-			is_ccache_enabled  \
-			upgrade_with_oprt
-
-		echo "upgrade_with_oprt"
-	)
-}
-
-ccache_reset_stats() {
-	is_ccache_enabled \
-		&& ccache --zero-stats
-}
-
-ccache_show_stats() {
-	is_ccache_enabled \
-		&& ccache --show-stats
-}
-
-is_ccache_enabled() {
-	[[ ${CCACHE_DIR+defined} && -x /usr/bin/ccache ]]
-}
-
-upgrade_with_oprt() {
-	# do not run install scripts in container
-	echo > ${HOME}/.cache/oprt/run_script
-
-	ccache_reset_stats
-	( set -o xtrace; oprt-update ) || exit 1
-	ccache_show_stats
-}
-
-upgrade_with_prt_get() {
-	# do not run install scripts in container
-	sed 's/runscripts.*//' --in-place /etc/prt-get.conf
-
-	ccache_reset_stats
-	( set -o xtrace; prt-get sysup ) || exit 1
-	ccache_show_stats
-
-	set -o xtrace
 	revdep $REVDEP_OPTS | xargs --no-run-if-empty prt-get update -fr
 }
 
-main
+run_me_in_container
